"""
Phase 6 — evidence formatting (pure, no I/O, no model calls).

Turns raw scores/features/contributions into a single structured evidence
dict. This is the ONLY place that defines the evidence schema consumed by
infer.py, explain_llm.py, and demo_case.py.

IMPORTANT: contributions here are local, additive TreeSHAP values from the
FROZEN Model A / Model A+B boosters (xgboost's exact pred_contribs). They
describe how each feature moved THIS prediction relative to the model's
base value -- they are not causal claims about the customer's behavior and
must not be presented as such.
"""

TOP_K_CONTRIBUTORS = 5

DISCLAIMER = (
    "This evidence is generated by frozen, previously-validated models "
    "(Phase 1-5, unchanged). Feature contributions are local model "
    "attributions (TreeSHAP), not causal explanations or proof of abuse. "
    "This is a synthetic benchmark system; scores/decisions require human "
    "judgement before any real action."
)


def top_contributors(contribs, feature_names, k=TOP_K_CONTRIBUTORS):
    """
    contribs: 1D array of length len(feature_names)+1 (last element is the
    bias/base-value term, already excluded here) from
    booster.predict(dmatrix, pred_contribs=True)[0].
    Returns top-k by absolute contribution magnitude.
    """
    pairs = list(zip(feature_names, contribs[:len(feature_names)]))
    pairs.sort(key=lambda p: abs(p[1]), reverse=True)
    out = []
    for name, val in pairs[:k]:
        out.append({
            "feature": name,
            "contribution_log_odds": float(val),
            "direction": "increases_risk" if val > 0 else "decreases_risk",
        })
    return out


def build_evidence(
    customer_id,
    as_of_day,
    feature_values,          # dict: feature_name -> raw value (behavioral + relational)
    risk_a, risk_b,
    threshold_a, threshold_b,
    contribs_a, contribs_b,  # top_contributors() output for each model
    decision, decision_basis,
):
    return {
        "case": {
            "customer_id": str(customer_id),
            "as_of_day": int(as_of_day),
        },
        "model_scores": {
            "model_a_behavioral": {
                "risk": float(risk_a),
                "threshold": float(threshold_a),
                "flagged": bool(risk_a >= threshold_a),
            },
            "model_a_plus_b_relational": {
                "risk": float(risk_b),
                "threshold": float(threshold_b),
                "flagged": bool(risk_b >= threshold_b),
            },
        },
        "decision": decision,
        "decision_basis": decision_basis,
        "features": feature_values,
        "top_contributors": {
            "model_a_behavioral": contribs_a,
            "model_a_plus_b_relational": contribs_b,
        },
        "disclaimer": DISCLAIMER,
    }